### ISSUE TITLE
PCSE00240 - Muramassa Rebirth US

### ISSUE THREAD

**Issue by dethboy** [ShumnoT/VitaCheatDatabase#19]
Anyone have any codes for this? Especially health? Thanks so much

**Comment by Smoker1** [comment]
This is the only Version on Speedfly
http://www.speedfly.cn/19936.html

**Comment by Smoker1** [comment]
Also on Codemasters Project Site:
http://www.codemasters-project.net/forum/forum/playstation-hacking/playstation-vita-hacking/code-vault-ps3-aa/2956-pcsg00150-muramasa-rebirth

**Comment by Smoker1** [comment]
PCSG00150 Muramasa Rebirth
09-24-2017, 04:25 PM
Hacked by ; Dask

Game ver 1.06 /1.07 (Chinese)
For Psvita Cheat
Mai dump option 5 to load game Or NoNpDrm
GameID: PCSG00150 (Chinese Version) (But also works for the US and and EU Version (Tested it myself)

_V0 Money 999999
$3202 8140B490 000001A4
$3200 00000000 00000200
$3300 00000000 000F423F

_V0 SoulS 999999
$3202 8140B490 000001A4
$3200 00000000 00000204
$3300 00000000 000F423F

_V0 Infinite Life
$8202 8140B490 000001A4
$8200 00000000 000001E8
$8800 00000000 00000000
$8602 8140B490 000001A4
$8600 00000000 000001EC
$8900 00000000 00000000

_V0 EXP 999999
$3202 8140B490 000001A4
$3200 00000000 000001FC
$3300 00000000 000F423F

_V0 Life Max 999999
$3202 8140B490 000001A4
$3200 00000000 000001EC
$3300 00000000 000F423F

_V0 Spirit 999999
$3202 8140B490 000001A4
$3200 00000000 00000208
$3300 00000000 000F423F

_V0 Strength 9999
$3102 8140B490 000001A4
$3100 00000000 00000210
$3300 00000000 0000270F

_V0 Vitality 9999
$3102 8140B490 000001A4
$3100 00000000 00000212
$3300 00000000 0000270F

_V0 Press <SQUARE> to Spiritual Energy Max
$C204 00000001 00008000
$7102 8140B490 0000007C
$7100 00000000 000003B0
$7702 00000000 00001770
$0003 00000024 00000000
$C204 00000001 00008000
$7102 8140B490 000001A8
$7100 00000000 00000558
$7702 00000000 00001770
$0003 0000000C 00000000

_V0 Swords Never Broken
$7002 8140B490 0000007C
$7000 00000000 000003B4
$7702 00000000 00000000
$0003 00000024 00000000
$7002 8140B490 000001A8
$7000 00000000 00000554
$7702 00000000 00000000
$0003 0000000C 00000000

_V0 Unlock All Swords
$7002 8140B490 0000007C
$7000 00000000 0000010F
$7702 00000000 00000001
$006C 00000001 00000000
$7002 8140B490 0000007C
$7000 00000000 0000018F
$7702 00000000 00000001
$006C 00000001 00000000
$7002 8140B490 0000007C
$7000 00000000 0000020F
$7702 00000000 00000001
$006C 00000001 00000000
$7002 8140B490 0000007C
$7000 00000000 0000028F
$7702 00000000 00000001
$006C 00000001 00000000
$7002 8140B490 0000007C
$7000 00000000 0000030F
$7702 00000000 00000001
$006C 00000001 00000000

**Comment by dethboy** [comment]
Thanks so much. I tested the codes as well and everything works perfectly. You are the greatest!!
